deploy-dev:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $PROD_SERVER_USER@$PROD_SERVER_IP "
      cd $STAFF_FRONT_NEW_PROJECT_PATH &&
      bash deploy $STAFF_DIST_FOLDER_PATH"
  only:
    - master
